<?xml version="1.0" encoding="utf-8"?><Database Name="BachHoaXanh_Store" Class="BachHoaXanhDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=162860-VHBSON;Initial Catalog=BachHoaXanh_Store;Integrated Security=True" SettingsObjectName="BLL_DAO.Properties.Settings" SettingsPropertyName="BachHoaXanh_StoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTDonDatHang" Member="CTDonDatHangs">
    <Type Name="CTDonDatHang">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonDatHang_CTDonDatHang" Member="DonDatHang" ThisKey="MaDH" OtherKey="MaDH" Type="DonDatHang" IsForeignKey="true" />
      <Association Name="SanPham_CTDonDatHang" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SieuThi" Member="SieuThis">
    <Type Name="SieuThi">
      <Column Name="MaST" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenST" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="SieuThi_DonDatHang" Member="DonDatHangs" ThisKey="MaST" OtherKey="MaST" Type="DonDatHang" />
      <Association Name="SieuThi_HoaDonBanHang" Member="HoaDonBanHangs" ThisKey="MaST" OtherKey="MaST" Type="HoaDonBanHang" />
      <Association Name="SieuThi_KhoHangKM" Member="KhoHangKMs" ThisKey="MaST" OtherKey="MaST" Type="KhoHangKM" />
      <Association Name="SieuThi_KhoSieuThi" Member="KhoSieuThis" ThisKey="MaST" OtherKey="MaST" Type="KhoSieuThi" />
      <Association Name="SieuThi_NhanVien" Member="NhanViens" ThisKey="MaST" OtherKey="MaST" Type="NhanVien" />
      <Association Name="SieuThi_PhieuXuatKho" Member="PhieuXuatKhos" ThisKey="MaST" OtherKey="MaST" Type="PhieuXuatKho" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuTraHang" Member="CTPhieuTraHangs">
    <Type Name="CTPhieuTraHang">
      <Column Name="MaPTH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="PhieuTraHang_CTPhieuTraHang" Member="PhieuTraHang" ThisKey="MaPTH" OtherKey="MaPTH" Type="PhieuTraHang" IsForeignKey="true" />
      <Association Name="SanPham_CTPhieuTraHang" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuXuatKho" Member="CTPhieuXuatKhos">
    <Type Name="CTPhieuXuatKho">
      <Column Name="MaPXK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhieuXuatKho_CTPhieuXuatKho" Member="PhieuXuatKho" ThisKey="MaPXK" OtherKey="MaPXK" Type="PhieuXuatKho" IsForeignKey="true" />
      <Association Name="SanPham_CTPhieuXuatKho" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHoaDonBanHang" Member="CTHoaDonBanHangs">
    <Type Name="CTHoaDonBanHang">
      <Column Name="MaHD" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KhuyenMai" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDonBanHang_CTHoaDonBanHang" Member="HoaDonBanHang" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDonBanHang" IsForeignKey="true" />
      <Association Name="SanPham_CTHoaDonBanHang" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHoaDonDatNCC" Member="CTHoaDonDatNCCs">
    <Type Name="CTHoaDonDatNCC">
      <Column Name="MaHDDat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDonDatNCC_CTHoaDonDatNCC" Member="HoaDonDatNCC" ThisKey="MaHDDat" OtherKey="MaHDDat" Type="HoaDonDatNCC" IsForeignKey="true" />
      <Association Name="SanPham_CTHoaDonDatNCC" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiLapPhieu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DonDatHang_CTDonDatHang" Member="CTDonDatHangs" ThisKey="MaDH" OtherKey="MaDH" Type="CTDonDatHang" />
      <Association Name="DonDatHang_PhieuXuatKho" Member="PhieuXuatKhos" ThisKey="MaDH" OtherKey="MaDH" Type="PhieuXuatKho" />
      <Association Name="SieuThi_DonDatHang" Member="SieuThi" ThisKey="MaST" OtherKey="MaST" Type="SieuThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBanHang" Member="HoaDonBanHangs">
    <Type Name="HoaDonBanHang">
      <Column Name="MaHD" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TongSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDonBanHang_CTHoaDonBanHang" Member="CTHoaDonBanHangs" ThisKey="MaHD" OtherKey="MaHD" Type="CTHoaDonBanHang" />
      <Association Name="SieuThi_HoaDonBanHang" Member="SieuThi" ThisKey="MaST" OtherKey="MaST" Type="SieuThi" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDonBanHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonDatNCC" Member="HoaDonDatNCCs">
    <Type Name="HoaDonDatNCC">
      <Column Name="MaHDDat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiLapPhieu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HoaDonDatNCC_CTHoaDonDatNCC" Member="CTHoaDonDatNCCs" ThisKey="MaHDDat" OtherKey="MaHDDat" Type="CTHoaDonDatNCC" />
      <Association Name="NhaCungCap_HoaDonDatNCC" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoHangKM" Member="KhoHangKMs">
    <Type Name="KhoHangKM">
      <Column Name="MaST" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayKM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaKM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SieuThi_KhoHangKM" Member="SieuThi" ThisKey="MaST" OtherKey="MaST" Type="SieuThi" IsForeignKey="true" />
      <Association Name="SanPham_KhoHangKM" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoSieuThi" Member="KhoSieuThis">
    <Type Name="KhoSieuThi">
      <Column Name="MaST" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SieuThi_KhoSieuThi" Member="SieuThi" ThisKey="MaST" OtherKey="MaST" Type="SieuThi" IsForeignKey="true" />
      <Association Name="SanPham_KhoSieuThi" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSP" Member="LoaiSPs">
    <Type Name="LoaiSP">
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiSP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LoaiSP_SanPham" Member="SanPhams" ThisKey="MaLoaiSP" OtherKey="MaLoaiSP" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Association Name="NhaCungCap_HoaDonDatNCC" Member="HoaDonDatNCCs" ThisKey="MaNCC" OtherKey="MaNCC" Type="HoaDonDatNCC" />
      <Association Name="NhaCungCap_SanPham" Member="SanPhams" ThisKey="MaNCC" OtherKey="MaNCC" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TenDN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_HoaDonBanHang" Member="HoaDonBanHangs" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDonBanHang" />
      <Association Name="SieuThi_NhanVien" Member="SieuThi" ThisKey="MaST" OtherKey="MaST" Type="SieuThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuTraHang" Member="PhieuTraHangs">
    <Type Name="PhieuTraHang">
      <Column Name="MaPTH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiLapPhieu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhieuTraHang_CTPhieuTraHang" Member="CTPhieuTraHangs" ThisKey="MaPTH" OtherKey="MaPTH" Type="CTPhieuTraHang" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuatKho" Member="PhieuXuatKhos">
    <Type Name="PhieuXuatKho">
      <Column Name="MaPXK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaST" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiLapPhieu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayXuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhieuXuatKho_CTPhieuXuatKho" Member="CTPhieuXuatKhos" ThisKey="MaPXK" OtherKey="MaPXK" Type="CTPhieuXuatKho" />
      <Association Name="DonDatHang_PhieuXuatKho" Member="DonDatHang" ThisKey="MaDH" OtherKey="MaDH" Type="DonDatHang" IsForeignKey="true" />
      <Association Name="SieuThi_PhieuXuatKho" Member="SieuThi" ThisKey="MaST" OtherKey="MaST" Type="SieuThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaVon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Isdeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SanPham_CTDonDatHang" Member="CTDonDatHangs" ThisKey="MaSP" OtherKey="MaSP" Type="CTDonDatHang" />
      <Association Name="SanPham_CTPhieuTraHang" Member="CTPhieuTraHangs" ThisKey="MaSP" OtherKey="MaSP" Type="CTPhieuTraHang" />
      <Association Name="SanPham_CTPhieuXuatKho" Member="CTPhieuXuatKhos" ThisKey="MaSP" OtherKey="MaSP" Type="CTPhieuXuatKho" />
      <Association Name="SanPham_CTHoaDonBanHang" Member="CTHoaDonBanHangs" ThisKey="MaSP" OtherKey="MaSP" Type="CTHoaDonBanHang" />
      <Association Name="SanPham_CTHoaDonDatNCC" Member="CTHoaDonDatNCCs" ThisKey="MaSP" OtherKey="MaSP" Type="CTHoaDonDatNCC" />
      <Association Name="SanPham_KhoHangKM" Member="KhoHangKMs" ThisKey="MaSP" OtherKey="MaSP" Type="KhoHangKM" />
      <Association Name="SanPham_KhoSieuThi" Member="KhoSieuThis" ThisKey="MaSP" OtherKey="MaSP" Type="KhoSieuThi" />
      <Association Name="LoaiSP_SanPham" Member="LoaiSP" ThisKey="MaLoaiSP" OtherKey="MaLoaiSP" Type="LoaiSP" IsForeignKey="true" />
      <Association Name="NhaCungCap_SanPham" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
</Database>